# Generated by Django 6.0.5 on 2026-06-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductID', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=100)),
                ('Added_Dts', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('RegionID', models.AutoField(primary_key=True, serialize=False)),
                ('RegionName', models.CharField(max_length=100)),
                ('Added_Dts', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
