# Generated by Django 6.0.5 on 2026-06-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('LeadID', models.AutoField(primary_key=True, serialize=False)),
                ('PersonName', models.CharField(max_length=100)),
                ('CompanyName', models.CharField(max_length=150)),
                ('ContactNo', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=254)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('BusinessNeed', models.CharField(max_length=255)),
                ('Lead_Gen_Date', models.DateField()),
                ('Added_By', models.CharField(max_length=100)),
                ('Added_Dts', models.DateTimeField()),
                ('ExecutiveID', models.IntegerField()),
            ],
            options={
                'db_table': 'Lead',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lead_Source',
            fields=[
                ('LeadSourceID', models.AutoField(primary_key=True, serialize=False)),
                ('LeadSourceName', models.CharField(max_length=100)),
                ('Added_By', models.CharField(max_length=100)),
                ('Added_Dts', models.DateTimeField()),
            ],
            options={
                'db_table': 'Lead_Source',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lead_Status',
            fields=[
                ('StatusID', models.AutoField(primary_key=True, serialize=False)),
                ('StatusName', models.CharField(max_length=100)),
                ('Added_By', models.CharField(max_length=100)),
                ('Added_Dts', models.DateTimeField()),
            ],
            options={
                'db_table': 'Lead_Status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product_Category',
            fields=[
                ('CategoryID', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(max_length=100)),
                ('Added_By', models.CharField(max_length=100)),
                ('Added_Dts', models.DateTimeField()),
            ],
            options={
                'db_table': 'Product_Category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('TerritoryID', models.AutoField(primary_key=True, serialize=False)),
                ('TerritoryName', models.CharField(max_length=100)),
                ('Added_By', models.CharField(max_length=100)),
                ('Added_Dts', models.DateTimeField()),
            ],
            options={
                'db_table': 'Territory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('LeadSourceID', models.AutoField(primary_key=True, serialize=False)),
                ('LeadSourceName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('StatusID', models.AutoField(primary_key=True, serialize=False)),
                ('StatusName', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'managed': False},
        ),
    ]
