# Generated by Django 6.0.5 on 2026-06-17 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leadapp', '0002_lead_lead_source_lead_status_product_category_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='Product',
        ),
        migrations.AlterModelTable(
            name='region',
            table='Region',
        ),
    ]
