# Generated by Django 6.0.5 on 2026-06-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadapp', '0003_alter_product_table_alter_region_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='StatusID',
            field=models.AutoField(db_column='StatusID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='status',
            name='StatusName',
            field=models.CharField(db_column='StatusName', max_length=100),
        ),
        migrations.AlterModelTable(
            name='status',
            table='Lead_Status',
        ),
    ]
