# Generated by Django 6.0.5 on 2026-06-20 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leadapp', '0004_alter_status_statusid_alter_status_statusname_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadsource',
            options={'managed': False},
        ),
    ]
